### ISSUE TITLE
Intel iGPU Hardware Acceleration Working But Not Being Recognized

### ISSUE THREAD

**Issue by pedrolara-boop** [feederbox826/stash-s6#26]
## Stash-S6 Intel iGPU Hardware Acceleration Issue

**System Details:**
- **OS:** Ubuntu Desktop 24.10 (Bare Metal)
- **Docker Container:** `stash-s6`
- **FFmpeg Version:** 7.0.2 (Jellyfin Build)
- **Intel GPU:** Integrated iGPU
- **VAAPI Driver:** Intel iHD

### **Issue Summary**
The Stash-S6 container is failing to initialize hardware acceleration with VAAPI and Intel Quick Sync Video (QSV). However, direct execution of `ffmpeg` within the container works, Stash fails to initialize hardware acceleration.

#### **NVENC (NVIDIA) Issues**
Expected since there is no NVIDIA hardware.

```
Please use -profile:a or -profile:v, -profile is ambiguous
Cannot load libcuda.so.1
Could not dynamically load CUDA
Error initializing filters
Error initializing a simple filtergraph
Error opening output file -.
Error opening output files: Operation not permitted
```

#### **Intel Quick Sync Video (QSV) Issues**
```
Device creation failed: -542398533.
Failed to set value 'qsv=hw' for option 'init_hw_device': Generic error in an external library
Error parsing global options: Generic error in an external library
```

#### **VAAPI (Video Acceleration API) Issues**
```
No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument
```

#### **V4L2M2M (Video4Linux) Issues**
```
Could not find a valid device
can't configure encoder
Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width, or height.
Error sending frames to consumers: Invalid argument
```

#### **VP9 Intel Quick Sync Video (QSV) Issues**
```
Device creation failed: -542398533.
Failed to set value 'qsv=hw' for option 'init_hw_device': Generic error in an external library
Error parsing global options: Generic error in an external library
```

#### **VP9 VAAPI Issues**
```
No VA display found for device /dev/dri/renderD128.
Device creation failed: -22.
Failed to set value '/dev/dri/renderD128' for option 'vaapi_device': Invalid argument
Error parsing global options: Invalid argument
```

#### **H264 VideoToolbox Issues**
```
Unrecognized option 'realtime'.
Error splitting the argument list: Option not found
```

#### **General Issue Summary**
```
[InitHWSupport] Supported HW codecs [0]:
```

#### **`vainfo` Output**
```
libva info: VA-API version 1.22.0
libva info: Trying to open /usr/lib/jellyfin-ffmpeg/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_22
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.22 (libva 2.22.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 25.1.0 (aa5ca48)
vainfo: Supported profile and entrypoints
  VAProfileH264Main               : VAEntrypointVLD
  VAProfileH264High               : VAEntrypointVLD
  VAProfileH264ConstrainedBaseline: VAEntrypointVLD
  VAProfileHEVCMain               : VAEntrypointVLD
  VAProfileHEVCMain10             : VAEntrypointVLD
  VAProfileVP9Profile0            : VAEntrypointVLD
```

#### **FFmpeg VAAPI Encoding Test (Inside Container)**
Command:
```
sudo docker exec -it stash-s6 ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 \
-f lavfi -i testsrc2 -vf 'format=nv12,hwupload' -c:v h264_vaapi -qp 22 output.mp4
```
Output:
```
frame=39003 fps=4587 q=-0.0 size=  104960KiB time=00:26:00.12 bitrate= 551.1kbits/s speed= 183x
```

### **Docker Compose Configuration**

I've used the example on the code, did my best to try to get working from my previous docker container.

```yaml
version: "3.9"
x-quicksync: &a1
  devices:
    - /dev/dri:/dev/dri
  group_add:
    - "44" # Video group (for Intel iGPU)
    - "992" # Render group (for Intel QuickSync)
services:
  stash:
    <<: *a1 # Enables QuickSync (Intel iGPU)
    image: ghcr.io/feederbox826/stash-s6:hwaccel # Using the hardware-accelerated image
    container_name: stash-s6
    restart: unless-stopped
    ports:
      - 9999:9999 # Web UI
    environment:
      - PUID=1000 # Set to match your user
      - PGID=1000 # Set to match your group
      - TZ=America/New_York # Change to your timezone
      - MIGRATE=TRUE # Enables automatic migration
      - STASH_CACHE=/cache
      - STASH_CONFIG_FILE=/config/config.yml
      - STASH_GENERATED=/generated
      - STASH_METADATA=/metadata
      - STASH_STASH=/data
    volumes:
      - /mnt/data:/data
      - /mnt/config:/config
      - /mnt/cache:/cache
networks: {}
```

**Comment by pedrolara-boop** [comment]
I was able to get Stash itself to recognize the hwaccel:

```
stash-s6  | INFO[2025-02-23 16:20:43] [InitHWSupport] Supported HW codecs [2]:
stash-s6  |     H264 Intel Quick Sync Video (QSV) Compatibility profile - h264_qsv
stash-s6  |     H264 VAAPI - h264_vaapi 
```

I've added my user to get the group permissions to:

`uid=1000 gid=1000(stash) groups=1000(stash),44(video),992`


Here is my updated compose.

```
services:
  stash:
    image: ghcr.io/feederbox826/stash-s6:hwaccel
    container_name: stash-s6
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 9999:9999
    environment:
      - TZ=America/New_York
      - STASH_CACHE=/cache
      - STASH_CONFIG_FILE=/config/config.yml
      - STASH_GENERATED=/generated
      - STASH_METADATA=/metadata
      - STASH_STASH=/data
      - LIBVA_DRIVER_NAME=iHD
      - VAAPI_DEVICE=/dev/dri/renderD128
      - STASH_HWACCEL=vaapi
    group_add:
      - "44"
      - "992"
    devices:
      - /dev/dri:/dev/dri
    volumes:
```
