### ISSUE TITLE
Intel Arc Pass through but no Acceleration

### ISSUE THREAD

**Issue by JohnSmithM7** [feederbox826/stash-s6#39]
Using HWaccel image, Arc A310 ECO GPU. Pass through works for jellyfin docker image, and is being read on the hwaccel end:

![Image](https://github.com/user-attachments/assets/fea98ab1-a99c-4bd5-aec1-87439deb80d1)

Here's the log also: [_stashapp_logs.txt](https://github.com/user-attachments/files/20584150/_stashapp_logs.txt)

And the yaml:
```
x-quicksync: &quicksync
  devices:
    - /dev/dri:/dev/dri
  group_add:
    - 109
    - 44
    - 103
    - 226
    - 993

x-win-quicksync: &win-quicksync
  devices:
    - /dev/dxg:/dev/dxg
  volumes:
    - /usr/lib/wsl:/usr/lib/wsl

x-nvenc: &nvenc
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

services:
  stash:
    container_name: stashapp
    # uncomment the applicable line for hardware acceleration
    <<: *quicksync
    # <<: *win-quicksync
    # <<: *nvenc
    image: ghcr.io/feederbox826/stash-s6:hwaccel
    ports:
      - 9999:9999
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=ETC/GMT+5
      - SKIP_NVIDIA_PATCH=TRUE
    #  - MIGRATE=TRUE
    volumes:
      - /media/Storage/Other:/media/
      - ./pip:/pip-install
      - ./config:/config
      - ./stash:/home/.stash
volumes:
  pip:
    external: true
  config:
    external: true
  stash:
    external: true
```
